# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HTML5 UP
brand: Editorial
email: email@example.com
phone: "+15555555555"
street_address: "12345 Anystreet Blvd."
city: "Anytown"
state: "D.C."
postal_code: "67890"
description: > # this means to ignore newlines until "baseurl:"
 A free and fully responsive site template by HTML5 UP and Jekyllized by Riyaad Azad.
baseurl: "/html5up-editorial-jekyll" # the subpath of your site, e.g. /blog
aboutme: We are a tech site that wants to provide the latest developments in Web.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_handle: jekyllrb
facebook_username: jekyllrb
dribbble_username: jekyllrb
instagram_username: jekyllrb
youtube_channel: jekyllrb
pinterest_username: jekyllrb
github_username:  jekyllrb
# google_analytics:

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

kramdown:
    input: GFM
    auto_ids: true
    hard_wrap: false
    syntax-highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
